### ISSUE TITLE
Eliminate Unneeded Characters in Data

### ISSUE THREAD

**Issue by NIACCInnovWork** [NIACCInnovWork/Workspace-Login-V1#2]
**Current:**
The application currently writes data to the file, one record per line, with section titles added in and vertical bars ( | aka pipe) dividing sections.  This was done to promote human readability; however, it slows down the data analysis process when brought into Excel.  

The pipe is a nonstandard character for delineating columns and required a manual entry of the character for parsing by excel.  A comma is typically used for *.csv files, but the risk of visitors entering a comma in their data indicates it would be better to use a tab character which is standard for *.txt files.

The additional text bring in the data as strings which then need to be "cleaned" to move extra characters and be interpreted as actual data.

**Requested:**
- Replace pipe ( " | " ) character with a tab character (ASCII character code 009) to separate values in exported files
- Remove the following section titles to keep the data clean
   - "Date: "
   - "Arrival Time: "
   - "Departure Time: "
   - "Usage of space: "
   - "Tools used: "
- _Optional:_ When writing data to the file, add these column headers as the first line with the ASCII tab character before writing in the data.

**Comment by rws-visuals** [comment]
This issue has been resolved. Data is condensed down to just the information with no labels. The excel file has these labels across row 1, and the data is automatically loaded below the labels into the proper sections. I suggest loading the files in from earliest to latest, so as to make organization easier since the newest added files add below the current data instead of above. Importing the data in this way will show the data from earliest data to latest data flowing from top to bottom.
